CREATE OR REPLACE DATABASE GIT_PRACTISE;
CREATE OR REPLACE SCHEMA GIT_PRACTISE.SAMPLE_SCHEMA;
CREATE OR REPLACE TABLE GIT_PRACTISE.SAMPLE_SCHEMA.DUMMY_SALES_TABLE
(
	ID INT,
	QTY INT,
	ORDER_DATE DATE,
	CITY VARCHAR
);